#spring.application.name=gymbackend
#spring.datasource.url=jdbc:postgresql://localhost:5432/gym
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


#spring.datasource.url=jdbc:postgresql://ep-falling-sunset-aoltybxb.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_BTjFJ6ycHV7f
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#spring.application.name=gymbackend
#spring.datasource.url=jdbc:postgresql://dpg-d7or5cl8nd3s739mnpr0-a.ohio-postgres.render.com:5432/gym_vaw2
#spring.datasource.username=gymuser
#spring.datasource.password=GzurJMnOjrnbtE4dRLH1pSA10aqx5z8B
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#server.port=${PORT:8080}


spring.application.name=gymbackend

# DON'T hardcode the URL and Password here. Use these variables:
spring.datasource.url=jdbc:${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port configuration
server.port=${PORT:8080}